[wokwi]
version = 1
elf = "build/esp32.esp32.esp32doit-devkit-v1/cp.ino.elf"
firmware = "build/esp32.esp32.esp32doit-devkit-v1/cp.ino.bin"

# WiFi Configuration
[[wifi]]
ssid = "Wokwi-GUEST"
password = ""
internet = true
channel = 6    # Set WiFi channel to 6 for faster connection

# Forward http://localhost:8280 to port 80 on the simulated ESP32:
[[net.forward]]
from = "0.0.0.0:8280"
to = "target:80"